const images = {
  logo: "/assets/sidebar/logo.svg",
  notifcation: "/assets/sidebar/Bell.svg",
  admin: "/assets/layout/admin.png",
  dashboard: "/assets/sidebar/dashboard.svg",
  usermgt: "/assets/sidebar/userMgt.svg",
  creditMgt: "/assets/sidebar/credit.svg",
  Loanmgt: "/assets/sidebar/loan.svg",
  loansDisbursement: "/assets/sidebar/loanBank.svg",
  Transactions: "/assets/sidebar/transaction.svg",
  balance: "/assets/sidebar/balance.svg",
  ShopMgt: "/assets/sidebar/shopMgt.svg",
  referral: "/assets/sidebar/referral.svg",
  tickets: "/assets/sidebar/tickets.svg",
  analytics: "/assets/sidebar/Analytics.svg",
  settings: "/assets/sidebar/setting.svg",
  logout: "/assets/sidebar/SignOut.svg",
  bell: "/assets/images/bell.svg",
  dots: "/assets/images/3dots.svg",
  cross: "/assets/images/cross.svg",
  arrow: "/assets/images/arrow.svg",
  users: "/assets/images/Users.png",
  rightarrow: "/assets/images/rightarrow.svg",
  tick: "/assets/images/tick.svg",
  minibundle: "/assets/images/minibundle.png",
  maxibundle: "/assets/images/maxibundle.png",
  plus: "/assets/images/plus.svg",
  minus: "/assets/images/minus.svg",
  Lightning: "/assets/images/Lightning.svg",
};

export default images;
